# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Permalinks
permalink:        pretty

# Setup
title:            bip20
tagline:          'bip20 - Academic webpage'
description:      'PhD student<br>
@<a href="http://www.bath.ac.uk/comp-sci/research/mathematical-foundations/" target="_blank">Computer Science</a><br>
@<a href="http://www.bath.ac.uk/" target="_blank">University of Bath</a>'
url:              http://hyde.getpoole.com
baseurl:          /

author:
  name:           'Mark Otto'
  url:            https://twitter.com/mdo

paginate:         5

# Custom vars
version:          2.1.0

github:
  repo:           https://github.com/poole/hyde
